version: '3'

services:
  web_server:
    build: Frontend
    image: web_server
    ports:
      - "80:80"
  api:
    build: Backend
    image: api
    ports:
      - "5001:5001"
  database:
    build: Database
    image: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: